name: Build & Deploy
 
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
 
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
    - uses: azure/docker-login@v2
      with:
        login-server: watch2getherimages.azurecr.io 
        username: ${{ secrets.ACR_REGISTRY_USERNAME }}
        password: ${{ secrets.ACR_REGISTRY_PASSWORD }}
    - name: build image
      run: docker build . -t watch2getherimages.azurecr.io/frontend
    - name: deploy
      run: docker push watch2getherimages.azurecr.io/frontend
