apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: accountdb
  name: accountdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: accountdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/individuele-db-network: "true"
        io.kompose.service: accountdb
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: example
          image: postgres
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres -d users -t 1
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          name: accountdb
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: accountdb-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: accountdb-cm0
          name: accountdb-cm0
