apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: accountservice
  name: accountservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: accountservice
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/individuele-client: "true"
        io.kompose.network/individuele-db-network: "true"
        io.kompose.service: accountservice
    spec:
      containers:
        - image: watch2getherimages.azurecr.io/individuele-accountservice:latest
          name: accountservice
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
      imagePullSecrets:
        - name: acr-secret
      restartPolicy: Always
