apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: nextfrontend
  name: nextfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextfrontend
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/individuele-client: "true"
        io.kompose.service: nextfrontend
    spec:
      containers:
        - image: watch2getherimages.azurecr.io/individuele-nextfrontend:latest
          name: frontend
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
      imagePullSecrets:
        - name: acr-secret
      restartPolicy: Always
