apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: videoservice
  name: videoservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: videoservice
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/individuele-client: "true"
        io.kompose.service: videoservice
    spec:
      containers:
        - image: watch2getherimages.azurecr.io/individuele-videoservice:latest
          name: videoservice
          ports:
            - containerPort: 5000
              hostPort: 5003
              protocol: TCP
      imagePullSecrets:
        - name: acr-secret
      restartPolicy: Always
